name: Populate Data Cache

on:
  schedule:
    # schedule build once per day
    - cron: "6 11 * * *"
  workflow_dispatch: # Allow to manually run a workflow
    inputs:
      forceRebuild:
        description: Force Rebuild
        required: false
        default: false
        type: boolean

jobs:
  build_data_cache:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        configuration: [Release]
        architecture: [x64]
    steps:
    - name: Check for data cache
      id: check-for-data-cache
      uses: actions/cache/restore@v3
      with:
        path: |
          OpenEnroth_GameData
        key: data-cache

    - name: Checkout private data
      if: steps.check-for-data-cache.outputs.cache-hit != 'true' || ${{inputs.forceRebuild}}
      uses: actions/checkout@v3
      with:
        repository: OpenEnroth/OpenEnroth_GameData
        path: OpenEnroth_GameData
        lfs: 'true' # .vid files are stored in LFS.
        token: '${{secrets.DATA_ACCESS_TOKEN}}'

    - name: Cache data
      if: steps.check-for-data-cache.outputs.cache-hit != 'true' || ${{inputs.forceRebuild}}
      uses: actions/cache/save@v3
      with:
        path: |
          OpenEnroth_GameData
        key: data-cache
