name: Windows_CI

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Debug, Release]
        Platform: [x64, Win32]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
        git submodule update --init
        mkdir out && cd out
        #cmake .. -G "NMake Makefiles" -A ${{ matrix.Platform }} -DCMAKE_BUILD_TYPE=${{ matrix.Configuration }}
        cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=${{ matrix.Configuration }}
        nmake check_style
        nmake
      shell: cmd
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: World_of_Might_and_Magic.exe
        path: out/World_of_Might_and_Magic.exe
